name: Android Sample

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  buildTest:
    name: Build JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        # Gradle 7 removed maven plugin, but the latest Android plugin compatible with Java 8 need it
        # so we can't test Android on Java 8 with Gradle 7+
        # https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin
        # https://mvnrepository.com/artifact/com.android.tools.build/gradle
        java_version: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Install latest jsonschema2pojo SNAPSHOT
        run: mvn -U -B install -DskipTests -Dmaven.javadoc.skip -Dmaven.site.skip
      - name: Build projects
        run: cd jsonschema2pojo-gradle-plugin/example/android && ./gradlew --info assembleDebug
